# Generated by Django 4.2.1 on 2023-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address_created_at_address_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='address',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='student',
            name='deleted_by_cascade',
        ),
        migrations.AddField(
            model_name='address',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
